title = "The Things Network Learn"

baseURL = "http://localhost/"

disableKinds = [
  "taxonomy",
  "taxonomyTerm",
  "RSS",
]

enableGitInfo = true

languageCode = "en-us"
languageName = "English"

pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "The Things Network Learn"
  keywords = []
  github_repository = "https://github.com/TheThingsNetwork/docs"
  github_repository_edit = "https://github.com/TheThingsNetwork/docs/blob/master/doc/content"
  tts_github_repository = "https://github.com/TheThingsNetwork/lorawan-stack"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.contributing]]
    name = "GitHub"
    url = "https://github.com/TheThingsNetwork/docs"
    weight = 1

  [[menu.contributing]]
    name = "Forum"
    url = "https://www.thethingsnetwork.org/forum"
    weight = 2

  [[menu.about_us]]
    name = "The Things Network"
    url = "https://www.thethingsnetwork.org"
    weight = 1

  [[menu.about_us]]
    name = "The Things Industries"
    url = "https://www.thethingsindustries.com"
    weight = 2

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/bulma"
    target = "assets/css/vendor/bulma"
